### ISSUE TITLE
font styling

### ISSUE THREAD

**Issue by jeevan-v-jijo** [georgevs56/github-Login-Page#1]
there are discrepancies in font styles with the original where it says "Sign in to GitHub".. I just tried out how to create an issue in GitHub...

**Comment by jeevan-v-jijo** [comment]
use this in head section
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300&display=swap" rel="stylesheet">

use this as the font family of Sign class
font-family: 'IBM Plex Sans', sans-serif;

this font is similar to the orginal one i guess... for "Sign in to GitHub"

**Comment by georgevs56** [comment]
I had issues with the fonts and I did not get time to check over it

**Comment by georgevs56** [comment]
Thanks for solving the issue. If you have done some changes just give a pull request by creating a new branch..

**Comment by georgevs56** [comment]
Again thanks for resolving the issue
